---
micronaut:
  application:
    name: partidas

---
mongodb:
  uri: "mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}"

---
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"

---
micronaut:
  io:
    watch:
      paths: src/main
      restart: true